name: Gerar APK Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalando dependências
        run: npm install
      - name: Build APK
        run: npx expo export --platform android
