name: Gerar APK Final
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalando Ferramentas
        run: |
          npm install -g expo-cli
          npm install
      - name: Criando Estrutura Android
        run: npx expo prebuild --platform android
      - name: Gerar APK
        run: cd android && ./gradlew assembleRelease
      - name: Enviar APK Pronto
        uses: actions/upload-artifact@v4
        with:
          name: App-Trampo-Certo
          path: android/app/build/outputs/apk/release/*.apk
